"""Initial migration.

Revision ID: 87153f53d553
Revises: 
Create Date: 2025-02-25 15:11:37.944314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87153f53d553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
